<template>
  <ul class="content">
    <li>滚动测试1</li>
    <li>滚动测试2</li>
    <li>滚动测试3</li>
    <li>滚动测试4</li>
    <li>滚动测试5</li>
    <li>滚动测试6</li>
    <li>滚动测试7</li>
    <li>滚动测试8</li>
    <li>滚动测试9</li>
    <li>滚动测试10</li>
    <li>滚动测试11</li>
    <li>滚动测试12</li>
    <li>滚动测试13</li>
    <li>滚动测试14</li>
    <li>滚动测试15</li>
    <li>滚动测试16</li>
    <li>滚动测试17</li>
    <li>滚动测试18</li>
    <li>滚动测试19</li>
    <li>滚动测试20</li>
    <li>滚动测试21</li>
    <li>滚动测试22</li>
    <li>滚动测试23</li>
    <li>滚动测试24</li>
    <li>滚动测试25</li>
    <li>滚动测试26</li>
    <li>滚动测试27</li>
    <li>滚动测试28</li>
    <li>滚动测试29</li>
    <li>滚动测试30</li>
    <li>滚动测试31</li>
    <li>滚动测试32</li>
    <li>滚动测试33</li>
    <li>滚动测试34</li>
    <li>滚动测试35</li>
    <li>滚动测试36</li>
    <li>滚动测试37</li>
    <li>滚动测试38</li>
    <li>滚动测试39</li>
    <li>滚动测试40</li>
    <li>滚动测试41</li>
    <li>滚动测试42</li>
    <li>滚动测试43</li>
    <li>滚动测试44</li>
    <li>滚动测试45</li>
    <li>滚动测试46</li>
    <li>滚动测试47</li>
    <li>滚动测试48</li>
    <li>滚动测试49</li>
    <li>滚动测试50</li>
    <li>滚动测试51</li>
    <li>滚动测试52</li>
    <li>滚动测试53</li>
    <li>滚动测试54</li>
    <li>滚动测试55</li>
    <li>滚动测试56</li>
    <li>滚动测试57</li>
    <li>滚动测试58</li>
    <li>滚动测试59</li>
    <li>滚动测试60</li>
    <li>滚动测试61</li>
    <li>滚动测试62</li>
    <li>滚动测试63</li>
    <li>滚动测试64</li>
    <li>滚动测试65</li>
    <li>滚动测试66</li>
    <li>滚动测试67</li>
    <li>滚动测试68</li>
    <li>滚动测试69</li>
    <li>滚动测试70</li>
    <li>滚动测试71</li>
    <li>滚动测试72</li>
    <li>滚动测试73</li>
    <li>滚动测试74</li>
    <li>滚动测试75</li>
    <li>滚动测试76</li>
    <li>滚动测试77</li>
    <li>滚动测试78</li>
    <li>滚动测试79</li>
    <li>滚动测试80</li>
    <li>滚动测试81</li>
    <li>滚动测试82</li>
    <li>滚动测试83</li>
    <li>滚动测试84</li>
    <li>滚动测试85</li>
    <li>滚动测试86</li>
    <li>滚动测试87</li>
    <li>滚动测试88</li>
    <li>滚动测试89</li>
    <li>滚动测试90</li>
    <li>滚动测试91</li>
    <li>滚动测试92</li>
    <li>滚动测试93</li>
    <li>滚动测试94</li>
    <li>滚动测试95</li>
    <li>滚动测试96</li>
    <li>滚动测试97</li>
    <li>滚动测试98</li>
    <li>滚动测试99</li>
    <li>滚动测试100</li>
  </ul>
</template>

<script>
  import BScroll from 'better-scroll'

  export default {
    name: "Category",
    created () {
      new BScroll()
    }
  }
</script>

<style scoped>

</style>